services:
  - type: web
    name: youtube-mp3
    env: node
    buildCommand: pip install yt-dlp && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
